name: jet
batch_size: 16
grad_accumulation_steps: 1
tokens: tokens/
tokenizer: tokenizers/16384.pkl
d_model: 16
d_mlp: 32
lr_max: 0.01
lr_schedule: onecycle
mask_type: causal
epochs: 1
n_blocks: 4
n_heads: 8
n_ctx: 16
overlap: 4
vocab_size: 2048
weight_decay: 0.0001
eff_batch_per_log: 100
seed: 90
n_workers: 2
log_per_val: -1

