name: jet
batch_size: 16
grad_accumulation_steps: 1
corpus: ipl_commentary
tokenizer_corpus: ipl_commentary
device: cpu
embed_dim: 16
ff_dim: 32
lr_max: 0.01
lr_schedule: onecycle
mask_type: causal
epochs: 1
num_blocks: 4
num_heads: 8
seq_len: 16
overlap: 4
vocab_size: 2048
weight_decay: 0.0001
eff_batch_per_log: 100
seed: 90
num_workers: 2
autocast: True

