name: jet
world_size: 2
batch_size: 16
grad_accumulation_steps: 2
corpus: ipl_commentary
tokenizer_corpus: ipl_commentary
device: cpu
embed_dim: 16
ff_dim: 32
lr_max: 0.01
lr_schedule: onecycle
mask_type: causal
max_iter: 1000
num_blocks: 4
num_heads: 8
seq_len: 16
vocab_size: 600
weight_decay: 0.0001
