# Use this file to configure the directory structure of any input and output from 
# `download.py`, `encode.py` and `train_model.py`.
# See `utils.files.PathFetcher` for the implementation of these templates. 
# Any arg parsed by the python script's arg parser can be use in your template configuration, as well as the current `time`.

dataset: './data/{dataset}/raw/'
dataset_config: './configs/project_datasets/{dataset}.yaml'
model: './models/{name}_{time}/model.pt'
tokenizer: '{tokenizer}'
tokens: '{tokens}'
model_config: './models/{name}_{time}/config.yaml'
wandb: '{name}_{time}'
